# Generated by Django 5.0.6 on 2024-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0004_alter_registration_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='team_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
