# Generated by Django 5.0.6 on 2024-05-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0008_remove_registration_user_registration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
