# Generated by Django 5.0.6 on 2024-05-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0010_alter_registration_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'permissions': [('ultra_register', 'User gets ultra registration')]},
        ),
    ]
